version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  db: # название моего имеджа
    image: postgres:12 # скачает image postgres 12 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
      - "./config/postgres/postgresMainDB/postgres.conf:/var/lib/postgresql/data/postgresql.conf"
      - "./config/postgres/postgresDBInit.sql:/docker-entrypoint-initdb.d/mrga_init.sql"
    ports: # порты
      - "5432:5432"
    networks:
      - service-network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data
  db-storage:
    image: postgres:latest
    volumes:
      - type: volume
        source: postgresstore-data
        target: /var/lib/postgresql/data
      - "./config/postgres/postgresFileStorageServiceDB/postgres.conf:/var/lib/postgresql/data/postgresql.conf"
      - "./config/postgres/postgresDBInit.sql:/docker-entrypoint-initdb.d/mrga_init.sql"
    ports:
      - "5433:5433"
    networks:
      - service-network
  db-chat:
    image: postgres:latest
    volumes:
      - type: volume
        source: postgreschat-data
        target: /var/lib/postgresql/data
      - "./config/postgres/postgresChatServiceDB/postgres.conf:/var/lib/postgresql/data/postgresql.conf"
      - "./config/postgres/postgresDBInit.sql:/docker-entrypoint-initdb.d/mrga_init.sql"

    ports:
      - "5434:5434"
    networks:
      - service-network

volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  redis-data:
    driver: local
  postgresstore-data:
    driver: local
  postgreschat-data:
    driver: local

networks:
  service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24
          gateway: 11.0.0.1