global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: docker_exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'golang'
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']

  - job_name: 'system'
    static_configs:
      - targets: ['docker.for.mac.localhost:9100']

