// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dataStruct "github.com/go-park-mail-ru/2023_1_MRGA.git/internal/app/data_struct"
	recommendation "github.com/go-park-mail-ru/2023_1_MRGA.git/internal/pkg/recommendation"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepositoryRec is a mock of IRepositoryRec interface.
type MockIRepositoryRec struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryRecMockRecorder
}

// MockIRepositoryRecMockRecorder is the mock recorder for MockIRepositoryRec.
type MockIRepositoryRecMockRecorder struct {
	mock *MockIRepositoryRec
}

// NewMockIRepositoryRec creates a new mock instance.
func NewMockIRepositoryRec(ctrl *gomock.Controller) *MockIRepositoryRec {
	mock := &MockIRepositoryRec{ctrl: ctrl}
	mock.recorder = &MockIRepositoryRecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryRec) EXPECT() *MockIRepositoryRecMockRecorder {
	return m.recorder
}

// CheckStatus mocks base method.
func (m *MockIRepositoryRec) CheckStatus(userId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockIRepositoryRecMockRecorder) CheckStatus(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockIRepositoryRec)(nil).CheckStatus), userId)
}

// GetLikes mocks base method.
func (m *MockIRepositoryRec) GetLikes(userId uint, history, reasons []uint, filters dataStruct.UserFilter) ([]recommendation.UserRecommend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikes", userId, history, reasons, filters)
	ret0, _ := ret[0].([]recommendation.UserRecommend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikes indicates an expected call of GetLikes.
func (mr *MockIRepositoryRecMockRecorder) GetLikes(userId, history, reasons, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikes", reflect.TypeOf((*MockIRepositoryRec)(nil).GetLikes), userId, history, reasons, filters)
}

// GetLikesCount mocks base method.
func (m *MockIRepositoryRec) GetLikesCount(userId uint, history, reasons []uint, filters dataStruct.UserFilter) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesCount", userId, history, reasons, filters)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikesCount indicates an expected call of GetLikesCount.
func (mr *MockIRepositoryRecMockRecorder) GetLikesCount(userId, history, reasons, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesCount", reflect.TypeOf((*MockIRepositoryRec)(nil).GetLikesCount), userId, history, reasons, filters)
}

// GetRecommendation mocks base method.
func (m *MockIRepositoryRec) GetRecommendation(userId uint, history, reasons, hashtags []uint, filters dataStruct.UserFilter) ([]recommendation.UserRecommend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendation", userId, history, reasons, hashtags, filters)
	ret0, _ := ret[0].([]recommendation.UserRecommend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendation indicates an expected call of GetRecommendation.
func (mr *MockIRepositoryRecMockRecorder) GetRecommendation(userId, history, reasons, hashtags, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendation", reflect.TypeOf((*MockIRepositoryRec)(nil).GetRecommendation), userId, history, reasons, hashtags, filters)
}

// GetRecommendedUser mocks base method.
func (m *MockIRepositoryRec) GetRecommendedUser(userId uint) (recommendation.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendedUser", userId)
	ret0, _ := ret[0].(recommendation.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendedUser indicates an expected call of GetRecommendedUser.
func (mr *MockIRepositoryRecMockRecorder) GetRecommendedUser(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendedUser", reflect.TypeOf((*MockIRepositoryRec)(nil).GetRecommendedUser), userId)
}

// GetStatus mocks base method.
func (m *MockIRepositoryRec) GetStatus(userId uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockIRepositoryRecMockRecorder) GetStatus(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockIRepositoryRec)(nil).GetStatus), userId)
}

// GetUserHistory mocks base method.
func (m *MockIRepositoryRec) GetUserHistory(userId uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHistory", userId)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHistory indicates an expected call of GetUserHistory.
func (mr *MockIRepositoryRecMockRecorder) GetUserHistory(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHistory", reflect.TypeOf((*MockIRepositoryRec)(nil).GetUserHistory), userId)
}
