name: Test and Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
      
    - name: Install make
      run: sudo apt-get install -y make

    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@latest

    - name: Install easyjson
      run: go install github.com/mailru/easyjson/...

    - name: Generate mocks and JSON serializers
      run: make generate

    - name: Check for uncommitted changes
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo "Found uncommitted changes after running go generate. Please commit the changes."
          git diff
          exit 1
        fi

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
      
    - name: Run linter
      run: make lint

    - name: Run unit tests
      run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: 95.163.180.8
        username: ubuntu
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd /home/ubuntu/2023_1_MRGA
          docker-compose stop
          git stash save
          git checkout main
          git pull origin
          docker-compose up -d
