name: Test on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
      
    - name: Install make
      run: sudo apt-get install -y make

    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0

    - name: Install easyjson
      run: |
        go get -u github.com/mailru/easyjson/...
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Generate mocks and JSON serializers
      run: go generate ./...

    - name: Check for uncommitted changes
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo "Found uncommitted changes after running go generate. Please commit the changes."
          git diff
          exit 1
        fi
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
      
    - name: Run linter
      run: make lint

    - name: Run tests with coverage
      run: |
        go mod tidy
        make cov
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
