name: Test on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
      
    - name: Install make
      run: sudo apt-get install -y make

    - name: Run tests with coverage
      run: |
        go mod tidy
        make cov
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
